experiment_name: advection_abblation1
equation: Advection
seeds: [123,234,345,456,567]

shared:
  model:
    params:
      modes: 16
      width: 64
  training:
    max_epochs: 100
    learning_rate: 0.001

experiments:
  - name: late_fusion_sparsity_sweep
    model:
      type: late_fusion
      params:
        num_hidden: 2
        library_type: polynomial
    sweep:
      model.params.sparsity_weight: [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
      model.params.order_states: [1, 2]
      model.params.order_parameters: [1, 2]
      